*****************************************************************************
*     fmodules.inc: include file for fortran modules
*****************************************************************************

      INTEGER*4 MAXREACH,MAXPRINT,MAXBOUND,MAXSEG,MAXSOLUTE,MAXFLOWLOC

      PARAMETER (MAXREACH = 1)
      PARAMETER (MAXPRINT = 1)
      PARAMETER (MAXBOUND = 10000)
      PARAMETER (MAXSEG = 5000)
      PARAMETER (MAXSOLUTE = 1)
      PARAMETER (MAXFLOWLOC = 1)

